function pts_n3 = sphere3d_samples(n)
k = floor((n/6)^(1/2));
[A,B] = meshgrid( linspace(-1,1,k), linspace(-1,1,k) );
A = A(:);
B = B(:);
L = ones(numel(A),1);
pts_n3 = [A, B, L;...
          A, B,-L;...
          A, L, B;...
          A,-L, B;...
          L, A, B;...
          -L,A, B];
pts_n3 = normr(pts_n3);
end